### ISSUE TITLE
Custom Cellpose Model

### ISSUE THREAD

**Issue by rhornb** [liulabspatial/2024_cycleHCR#1]
Dear @krokicki, 

I was wondering if you could upload the custom-trained cellpose model that was used to segment the mouse embryos in the [Cellpose_MouseEmbryo_3D](https://github.com/liulabspatial/cycleHCR/blob/main/jupyter_notebook/Cellpose_MouseEmbryo_3D.ipynb) notebook? 

I would be really interested to try it out!

Best,
Ruth

**Comment by krokicki** [comment]
Hi Ruth,

Thanks for reaching out! The model used in that notebook is here:
https://figshare.com/articles/dataset/Mouse_E6_5_cellpose/26927761?file=48983398

The other models are here:
https://figshare.com/articles/dataset/Hippocampus_cellpose/25772805?file=46177713

Best regards,
Konrad

**Comment by rhornb** [comment]
Hey @krokicki, 

awesome, thanks a lot!

Cheers, 
Ruth
